### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Johnng007** [chvancooten/follina.py#20]
got a TypeError
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30580457/171654126-2d7147ae-6c68-4518-a8cc-32089849cb6f.png)

**Comment by chvancooten** [comment]
This is likely related to your python version, could you try upgrading to 3.9 and try again?

**Comment by Johnng007** [comment]
Yeah it was the python version, works like a charm now!!!
