### ISSUE TITLE
正常运行，但是无法弹出计算器

### ISSUE THREAD

**Issue by qiuluo-oss** [chvancooten/follina.py#7]

**Comment by qiuluo-oss** [comment]
![image](https://user-images.githubusercontent.com/72497146/171131011-4a765710-457c-444d-939b-e4a2a8a81c85.png)
word打开后没有反弹计算器
![image](https://user-images.githubusercontent.com/72497146/171131138-cc7d8c73-64f0-41f2-b241-0d653ff59c77.png)

**Comment by qiuluo-oss** [comment]
office是2016版本
![image](https://user-images.githubusercontent.com/72497146/171131396-e4af4e44-4683-448c-bd90-74a469e414ab.png)

**Comment by l1b3ri** [comment]
Is Word the latest version?

**Comment by chvancooten** [comment]
Closing, see https://github.com/chvancooten/follina.py/issues/5
